//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Авторизация
{
    using System;
    using System.Collections.Generic;
    
    public partial class Допольнительная_информация
    {
        public int Код_допольнительной_информации { get; set; }
        public Nullable<int> Код_пользователя { get; set; }
        public Nullable<int> Серия_паспорта { get; set; }
        public Nullable<int> Номер_паспорта { get; set; }
        public string Email { get; set; }
        public Nullable<int> Номер_страховой_компании { get; set; }
        public Nullable<int> Номер_страхового_полиса { get; set; }
        public Nullable<int> Код_типа_страхового_полиса { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Страховой_полис Страховой_полис { get; set; }
    }
}
