//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Авторизация
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int Код_заказа { get; set; }
        public Nullable<int> Код_услуги { get; set; }
        public Nullable<System.DateTime> Дата_создания_заказа { get; set; }
        public Nullable<int> Код_статуса_заказа { get; set; }
        public string Время_выполнения_заказа { get; set; }
        public Nullable<int> Код_пользователя { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Статус_заказа Статус_заказа { get; set; }
    }
}
