//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Авторизация
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оказанные_услуги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Оказанные_услуги()
        {
            this.Статус_заказа = new HashSet<Статус_заказа>();
        }
    
        public int Код_оказанной_услуги { get; set; }
        public Nullable<System.DateTime> Дата_оказаной_услуги { get; set; }
        public Nullable<int> Код_заказа { get; set; }
        public Nullable<int> Код_сотрудника { get; set; }
        public Nullable<int> Код_анализатора { get; set; }
        public Nullable<int> Код_услуги { get; set; }
        public string Результат { get; set; }
    
        public virtual Анализатор Анализатор { get; set; }
        public virtual Статус_услуги Статус_услуги { get; set; }
        public virtual Услуги Услуги { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Статус_заказа> Статус_заказа { get; set; }
    }
}
