//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Авторизация
{
    using System;
    using System.Collections.Generic;
    
    public partial class Работа_с_биоматериаломи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Работа_с_биоматериаломи()
        {
            this.Пользователи = new HashSet<Пользователи>();
        }
    
        public int Код_взятия_материала { get; set; }
        public Nullable<System.DateTime> Дата_взятия { get; set; }
        public string Вид_биоматериала { get; set; }
        public Nullable<int> Код_сотрудника_взявшего_биоматериал { get; set; }
        public Nullable<int> Код_должности { get; set; }
        public string Наименование { get; set; }
    
        public virtual Должность Должность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пользователи> Пользователи { get; set; }
    }
}
