//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Авторизация
{
    using System;
    using System.Collections.Generic;
    
    public partial class Страховой_полис
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Страховой_полис()
        {
            this.Допольнительная_информация = new HashSet<Допольнительная_информация>();
        }
    
        public int Номер_страхового_полиса { get; set; }
        public string Тип_полиса { get; set; }
        public Nullable<int> Номер_страховой_компании { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Допольнительная_информация> Допольнительная_информация { get; set; }
        public virtual Страховая_компания Страховая_компания { get; set; }
    }
}
